### ISSUE TITLE
[BUG] jinja2.exceptions.UndefinedError: 'mkdocs.config.defaults.MkDocsConfig object' has no attribute 'share'

### ISSUE THREAD

**Issue by pawamoy** [WSOFT-Project/lantana#48]
Hello, I'm building a [gallery of MkDocs themes](https://pawamoy.github.io/mkdocs-gallery/).

Lantana seems currently broken, here are the logs I'm getting when trying to build a basic site with it:

```
WARNING -  Template skipped: 'version.json' not found in theme directories.
ERROR   -  Error building page 'index.md': 'mkdocs.config.defaults.MkDocsConfig object' has no attribute 'share'
Traceback (most recent call last):
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 232, in _build_page
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/lantana/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/lantana/base.html", line 157, in top-level template code
    {% block main_content %}
^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/lantana/main.html", line 101, in block 'main_content'
    <li><button class="btn dropdown-item" onclick="share_to_twitter('{% if page.title %}{{ page.title }} | {% endif %}{{ config.site_name }}','{{ config.share.twitter_params }}');"><i class="bi bi-twitter"></i>&nbsp;Twitter</button></li>
^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'mkdocs.config.defaults.MkDocsConfig object' has no attribute 'share'
```

Could you take a look and let me know if it needs additional configuration?

Here is an archive containing the docs and configuration:

[lantana.tar.gz](https://github.com/WSOFT-Project/lantana/files/12765171/lantana.tar.gz)

```
tar xvzf lantana.tar.gz
cd lantana
python -m venv .venv
. .venv/bin/activate
pip install mkdocs
pip install $(mkdocs get-deps)
mkdocs build
```

**Comment by taiseiue** [comment]
Thanks for the report. Sorry for the delay in noticing. It appears to be a glitch due to the "share. twitter_params" not being set. As a temporary solution, please add the following line to `mkdocs.yml`We will fix this bug in the next few days.

```md
share:
    twitter_params : ''
```
